version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mendesxx.ti@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8080:80
