version: "3.7"
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: gobarber
    ports:
      - 5434:5432

  mongobarber:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  redisbarber:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
